// <auto-generated />
using System;
using EventBookingManagementSystem_Backend.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventBookingManagementSystem_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250425062207_initial4")]
    partial class initial4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventBookingManagementSystem_Backend.DB.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssetStatus")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Asset");
                });

            modelBuilder.Entity("EventBookingManagementSystem_Backend.DB.Entities.Asset_Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ItemId");

                    b.ToTable("Asset_Item");
                });

            modelBuilder.Entity("EventBookingManagementSystem_Backend.DB.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("end_time")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("start_time")
                        .HasColumnType("time");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("EventBookingManagementSystem_Backend.DB.Entities.Booking_Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<Guid>("assetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("bookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("end_time")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("start_time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("assetId");

                    b.HasIndex("bookingId");

                    b.ToTable("Booking_Asset");
                });

            modelBuilder.Entity("EventBookingManagementSystem_Backend.DB.Entities.Booking_Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<Guid>("BookingId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<Guid>("packageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookingId1");

                    b.HasIndex("packageId");

                    b.ToTable("Booking_Package");
                });

            modelBuilder.Entity("EventBookingManagementSystem_Backend.DB.Entities.Booking_Package_Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BookingPackageId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<Guid>("booking_packageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("itemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("booking_packageId");

                    b.HasIndex("itemId");

                    b.ToTable("Booking_Package_Item");
                });

            modelBuilder.Entity("EventBookingManagementSystem_Backend.DB.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("item_CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("item_CategoryId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("EventBookingManagementSystem_Backend.DB.Entities.Item_Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Item_Category");
                });

            modelBuilder.Entity("EventBookingManagementSystem_Backend.DB.Entities.Item_Price", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("assetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("asset_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("base_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("price_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ItemId");

                    b.HasIndex("assetId");

                    b.ToTable("Item_Price");
                });

            modelBuilder.Entity("EventBookingManagementSystem_Backend.DB.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("EventBookingManagementSystem_Backend.DB.Entities.Package_Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("item")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ItemId");

                    b.HasIndex("PackageId");

                    b.ToTable("Package_Item");
                });

            modelBuilder.Entity("EventBookingManagementSystem_Backend.DB.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EventBookingManagementSystem_Backend.DB.Entities.Asset_Item", b =>
                {
                    b.HasOne("EventBookingManagementSystem_Backend.DB.Entities.Asset", "asset")
                        .WithMany("Asset_Items")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventBookingManagementSystem_Backend.DB.Entities.Item", "item")
                        .WithMany("Asset_Items")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("asset");

                    b.Navigation("item");
                });

            modelBuilder.Entity("EventBookingManagementSystem_Backend.DB.Entities.Booking_Asset", b =>
                {
                    b.HasOne("EventBookingManagementSystem_Backend.DB.Entities.Asset", "asset")
                        .WithMany("Booking_Assets")
                        .HasForeignKey("assetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventBookingManagementSystem_Backend.DB.Entities.Booking", "booking")
                        .WithMany()
                        .HasForeignKey("bookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("asset");

                    b.Navigation("booking");
                });

            modelBuilder.Entity("EventBookingManagementSystem_Backend.DB.Entities.Booking_Package", b =>
                {
                    b.HasOne("EventBookingManagementSystem_Backend.DB.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventBookingManagementSystem_Backend.DB.Entities.Package", "package")
                        .WithMany()
                        .HasForeignKey("packageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("package");
                });

            modelBuilder.Entity("EventBookingManagementSystem_Backend.DB.Entities.Booking_Package_Item", b =>
                {
                    b.HasOne("EventBookingManagementSystem_Backend.DB.Entities.Booking_Package", "booking_package")
                        .WithMany()
                        .HasForeignKey("booking_packageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventBookingManagementSystem_Backend.DB.Entities.Item", "item")
                        .WithMany("Booking_Package_Items")
                        .HasForeignKey("itemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("booking_package");

                    b.Navigation("item");
                });

            modelBuilder.Entity("EventBookingManagementSystem_Backend.DB.Entities.Item", b =>
                {
                    b.HasOne("EventBookingManagementSystem_Backend.DB.Entities.Item_Category", "item_Category")
                        .WithMany("Items")
                        .HasForeignKey("item_CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("item_Category");
                });

            modelBuilder.Entity("EventBookingManagementSystem_Backend.DB.Entities.Item_Price", b =>
                {
                    b.HasOne("EventBookingManagementSystem_Backend.DB.Entities.Item", "item")
                        .WithMany("Item_Prices")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventBookingManagementSystem_Backend.DB.Entities.Asset", "asset")
                        .WithMany("Item_Prices")
                        .HasForeignKey("assetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("asset");

                    b.Navigation("item");
                });

            modelBuilder.Entity("EventBookingManagementSystem_Backend.DB.Entities.Package_Item", b =>
                {
                    b.HasOne("EventBookingManagementSystem_Backend.DB.Entities.Asset", "asset")
                        .WithMany("Package_Items")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventBookingManagementSystem_Backend.DB.Entities.Item", null)
                        .WithMany("Package_Items")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventBookingManagementSystem_Backend.DB.Entities.Package", "package")
                        .WithMany("Package_Items")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("asset");

                    b.Navigation("package");
                });

            modelBuilder.Entity("EventBookingManagementSystem_Backend.DB.Entities.Asset", b =>
                {
                    b.Navigation("Asset_Items");

                    b.Navigation("Booking_Assets");

                    b.Navigation("Item_Prices");

                    b.Navigation("Package_Items");
                });

            modelBuilder.Entity("EventBookingManagementSystem_Backend.DB.Entities.Item", b =>
                {
                    b.Navigation("Asset_Items");

                    b.Navigation("Booking_Package_Items");

                    b.Navigation("Item_Prices");

                    b.Navigation("Package_Items");
                });

            modelBuilder.Entity("EventBookingManagementSystem_Backend.DB.Entities.Item_Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("EventBookingManagementSystem_Backend.DB.Entities.Package", b =>
                {
                    b.Navigation("Package_Items");
                });
#pragma warning restore 612, 618
        }
    }
}
